#include "mcpe/world/level/tile/Tile.h"

Tile* Tile::redstoneRail;
Tile* Tile::pistonSticky;
Tile* Tile::pistonNormal;
Tile* Tile::pistonArm;
Tile* Tile::pistonMoving;
Tile* Tile::notGate_off;
Tile* Tile::notGate_on;
Tile* Tile::offlamp;
Tile* Tile::onlamp;
Tile* Tile::button;
Tile* Tile::buttonWood;
Tile* Tile::pressurePlate_stone;
Tile* Tile::pressurePlate_wood;
Tile* Tile::pressurePlate_gold;
Tile* Tile::pressurePlate_iron;
Tile* Tile::lever;
Tile* Tile::diode_off;
Tile* Tile::diode_on;
